/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'root' at '7/7/16 10:24 PM' with Gradle 2.13
 *
 * @author root, @date 7/7/16 10:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
